version: '3'
services:
  hadoop:
    build: hadoop
    command: bash -c "./boot.sh && ./sbin/httpfs.sh start && ./bin/hdfs namenode"
    volumes:
      - hdfs-volume:/tmp/hadoop-root
      - ./hadoop/etc:/hadoop/etc
  hadoop-datanode:
    image: spark_hadoop
    command: bash -c "./boot.sh && ./bin/hdfs datanode"
    volumes:
      - hdfs-data-volume:/tmp/hadoop-root
      - ./hadoop/etc:/hadoop/etc
  mysql:
    image: mysql:5.7
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./db/mysql:/var/lib/mysql
  spark:
    build: spark
    command: "/spark-bin/bin/spark-class org.apache.spark.deploy.master.Master"
    ports:
      - 2280:8080
    volumes:
      - ./spark/conf:/spark-bin/conf
  spark-slave:
    image: spark_spark
    command: "/spark-bin/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077"
    volumes:
      - ./spark/conf:/spark-bin/conf
  dev:
    build: dev
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - code-volume:/code
      - ./spark/conf:/spark-bin/conf
      - .IdeaIC2017.1:/home/dev/.IdeaIC2017.1
      - .IdeaIC.java:/home/dev/.java
      - .ivy2:/home/dev/.ivy2
      - .sbt:/home/dev/.sbt
      - /boxes/idea:/home/dev/idea
      - .zsh_history:/home/dev/.zsh_history
      - .zshrc:/home/dev/.zshrc
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.ssh:/home/dev/.ssh
      - ~/.gitconfig:/home/dev/.gitconfig
    links:
      - hadoop
      - hadoop-datanode
      - mysql
      - spark
      - spark-slave
volumes:
  code-volume:
    driver: local
  hdfs-volume:
    driver: local
  hdfs-data-volume:
    driver: local
