version: '3'
services:
  dns:
    build: dnscrypt
    volumes:
      - ./dnscrypt/config.conf:/Pcap_DNSProxy/Source/Release/Config.conf
    networks:
      default:
        ipv4_address: 172.98.0.2
  geoip:
    image: fiorix/freegeoip
    command: '-http 0.0.0.0:80'
    ports:
      - 9880:80
    networks:
      default:
        ipv4_address: 172.98.0.3
  ss:
    image: mritd/shadowsocks
    command: '-m "ss-local" -s "-c /config.json -s shadowbox-hk" -x -e "kcpclient" -k "-r shadowbox-hk:9091 -l :9091 -mode fast2"'
    # command: '-m "ss-local" -s "-c /config.json"'
    volumes:
      - /boxes/shadowsocks/shadowbox-config.json:/config.json
      - /etc/hosts:/etc/hosts
    ports:
      - 1080:1080
    networks:
      default:
        ipv4_address: 172.98.0.4
  privoxy:
    build: toolbox
    command: 'privoxy --no-daemon /etc/privoxy/config'
    volumes:
      - ./privoxy-config:/etc/privoxy/config
    links:
      - ss
    ports:
      - 8118:8118
    networks:
      default:
        ipv4_address: 172.98.0.5
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.98.0.0/16
