version: '3'
services:
  privoxy:
    image: teanoon/toolbox
    command: 'privoxy --no-daemon /etc/privoxy/config'
    volumes:
      - ./privoxy-config:/etc/privoxy/config
    ports:
      - 8118:8118
  geoip:
    image: fiorix/freegeoip
    command: '-http 0.0.0.0:80'
    ports:
      - 9880:80
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.98.0.0/16
