version: '3'
services:
  mysql:
    image: mysql:5.7
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8091:80
  app:
    image: teanoon/dot-cms
    environment:
      DOTCMS_HOME: '/home/dev/app'
    volumes:
      - ./dotcms-app:/home/dev/app
      - ./.zshrc:/home/dev/.zshrc
      - ./.zsh_history:/home/dev/.zsh_history
    ports:
      - 8092:8080
    links:
      - mysql
      - phpmyadmin
